### ISSUE TITLE
请教一个有关pg_class被vacuum full的问题

### ISSUE THREAD

**Issue by rendaoyuan** [digoal/blog#102]
德哥您好，看了您很多博客，受益匪浅，其中这篇有关表膨胀清理的博客（https://github.com/digoal/blog/blob/master/201606/20160615_01.md?spm=a2c6h.12873639.0.0.61aa40c6oRUIFn&file=20160615_01.md）引起我的注意，因为我之前对我们的Greenplum数据库中pg_class元表做过vacuum full，我查了下，pg_class的记录的确被排到了后边。我想请教下，pg_class表中，pg_class等多元表的记录被排到末端，会造成什么后果？

以上，感谢~

**Comment by digoal** [comment]
GP基于PG8.2的时候会有问题, 主要是要知道pg_class这个元数据的索引, 那么就得查pg_class这个元数据, 遍历之后得到它对应的索引是哪个, 然后才能去进行索引检索. 会导致加载的时候有性能问题. 
不知道现在的GP版本有没有解决?

**Comment by rendaoyuan** [comment]
明白了，感谢答复。前几天问了一下原厂，陈淼回复我说6版本已经没有这个问题了。
