### ISSUE TITLE
修改storage_parameter参数问题

### ISSUE THREAD

**Issue by Tsukiand** [digoal/blog#108]
现在我需要修改某个table的storage_parameter参数

ALTER TABLE x SET (autovacuum_vacuum_scale_factor = 0.01);
ALTER TABLE x SET (fillfactor = 10);

请教一下这些修改的参数在什么时候会生效？我在官网看到的说法是执行 VACUUM FULL 或者 CLUSTER之后就能生效
我在想是不是下一次执行Auto Vacuum之后这些配置也能生效？

我实际操作时候 我改变了 某个表的autovacuum_vacuum_scale_factor，其实我没有执行VACUUM FULL或者CLUSTER，但是实际上这个参数已经生效了，但是我不确定这个参数生效是否和Auto Vacuum或者其他什么动作有关联，也不确定这个参数是在哪个时间点生效的。

**Comment by digoal** [comment]
立即生效, 但是已有page不会受到影响, 直到发生table rewrite的动作
