### ISSUE TITLE
postgres集群HA自动切换

### ISSUE THREAD

**Issue by LuM2016** [digoal/blog#11]
你好，请问如何不使用第三方工具实现postgres集群HA自动切换呢？手册里面有提到。可以使用一种简单的超时功能， 特别是和主服务器上已知的archive_timeout设置一起（26.3 故障转移）。但是没有给出具体方法。请大神指点。谢谢。

**Comment by digoal** [comment]
主备角色自动切换，是需要第三方仲裁、FENCE设备(DNS\LVS\主机电源管理都可以) 的，否则很容易出现脑裂。
