### ISSUE TITLE
基于PostgreSQL创业的公司有那些

### ISSUE THREAD

**Issue by mawenbin666** [digoal/blog#118]
德哥 你好 ，
        请教个问题：PostgreSQL数据库是最先进的开源数据库，那么基于postgresql创业的公司有那些呢？或者说在哪里查看呢？

**Comment by digoal** [comment]
PostgreSQL数据库是最先进的开源数据库和基于postgresql创业的公司有那些有什么逻辑关系?

**Comment by digoal** [comment]
以下是一些基于PostgreSQL创业公司的商业模式：

TimescaleDB：TimescaleDB是一个开源的时序数据库，通过提供企业级时序数据存储解决方案，为企业提供高效、可靠的时序数据分析服务。其商业模式是基于开源软件产品提供软件维护、支持和咨询服务，以及提供基于订阅模式的高级功能和扩展支持服务。

Citus Data：Citus Data是一个分布式数据库解决方案提供商，提供在云端运行的高性能的分布式数据库服务。其商业模式是基于开源软件产品提供数据库托管、支持和咨询服务，以及提供基于订阅模式的高级功能和扩展支持服务。

Crunchy Data：Crunchy Data是一个PostgreSQL数据库解决方案提供商，提供基于PostgreSQL的高可用性、高性能、可扩展性的数据库解决方案。其商业模式是基于开源软件产品提供数据库托管、支持和咨询服务，以及提供基于订阅模式的高级功能和扩展支持服务。

ZomboDB：ZomboDB是一个基于PostgreSQL的全文搜索引擎，其商业模式是基于订阅模式提供高级功能和扩展支持服务。

EnterpriseDB：EnterpriseDB是一个PostgreSQL数据库解决方案提供商，提供商业级PostgreSQL数据管理、支持和咨询服务。其商业模式是基于订阅模式提供高级功能和扩展支持服务。

6.2ndQuadrant：2ndQuadrant是一个PostgreSQL数据库解决方案提供商，提供高可用性、性能优化和数据库管理等服务。其商业模式是基于订阅模式提供高级功能和扩展支持服务。

Cybertec：Cybertec是一个全球性的PostgreSQL服务提供商，提供数据库咨询、支持和培训等服务。其商业模式是基于订阅模式提供高级功能和扩展支持服务。
这些公司的商业模式主要是基于订阅模式，提供高级功能和扩展支持服务，同时也提供数据库托管、支持和咨询服务等。此外，还有一些公司基于PostgreSQL开发了自己的商业软件产品，并提供相应的服务和支持，如PostGIS、pgAdmin等。
