### ISSUE TITLE
limit 1 导致查询变慢

### ISSUE THREAD

**Issue by Aricyin** [digoal/blog#123]
请教下德哥，我有一条sql，在不加limit 1 的情况下查询很快，几十ms后告诉我没有结果，但是加了limit 1 之后 会需要执行4s左右再返回没有结果，这个原因是啥，正确的优化手段应该是什么，平时写代码是不是要避免这种写法。

**Comment by digoal** [comment]
分析方法: 看执行计划, Limit 1 会改变代价, 导致执行计划的变化.
