### ISSUE TITLE
德哥你好，请问您知道哪里可以给psql优化器提建议吗？

### ISSUE THREAD

**Issue by ruiruige** [digoal/blog#15]
我们是9.2.5，有个这么个sql
select DISTINCT 普通字段，主键 from 表 limit 1000 order by 主键

查了一下资料，distinct 好像可以用hash 和sort来实现，优化器又看到我有order by，就用了sort
实际上DISTINCT字段是多余的，
这种情况按我理解在重写的时候就得给他干掉
能给优化器去提建议吗？

**Comment by digoal** [comment]
HI, 可以的，你可以给社区发个邮件，这是邮件列表。
