### ISSUE TITLE
(小白求问)imgsmlr 插件安装失败

### ISSUE THREAD

**Issue by chencong-hakka** [digoal/blog#16]
按照文档
到 “create extension imgsmlr” 的时候，报错：
root=# create extension imgsmlr;
ERROR:  could not access file "$libdir/imgsmlr": No such file or directory
请问是这个 libdir 是怎么设置的！！

**Comment by Gradven** [comment]
同问啊，错误:  无法访问文件 "$libdir/imgsmlr": 没有那个文件或目录  。
你解决了么
