### ISSUE TITLE
请教，关于使用convert函数生成字节流的问题

### ISSUE THREAD

**Issue by Helmsman89** [digoal/blog#19]
0看完文章，很感谢！现在遇到一个问题，请教下
1查询“金”在GBK中的编码是BDF0，现在在数据库中使用convert函数(转换成GBK)，转换后的结果是"\275\360"(可见下方代码，这三条数据得到的是一样的结果)，这个结果感觉和GBK中的编码值对不上，请帮忙看下是哪里出了问题？
2个人猜想以下方面，但是没有经验，能否帮忙看下
  (1)第三个字段的数据类型定义的不对
  (2)函数用的不对
  (3)该显示受到客户端编码类型的影响
  (4)字节流，和真实的值要经过转换

代码：
create table tbl_h
(
id int  primary key,
wenzi varchar(30), 
code bytea
)

insert into tbl_h values(1,'金',convert('金'::bytea,'UTF8','GBK'));
insert into tbl_h values(2,'金',convert('金','UTF8','GBK'));
insert into tbl_h values(3,'金',convert_to('金','GBK'));

结果
id     wenzi                code
 1        金                   \275\360
 2        金                   \275\360
 3        金                   \275\360

**Comment by Helmsman89** [comment]
@digoal

**Comment by Helmsman89** [comment]
@digoal ，刚有人在网上查到了，数据库中的值是以8进制存储的。

**Comment by digoal** [comment]
https://github.com/digoal/blog/blob/master/201908/20190813_01.md
不同的字符集，字符占用的字节长度可能不一样，值也可能不一样
