### ISSUE TITLE
http://pan.baidu.com/s/1pKVCgHX 連結失效

### ISSUE THREAD

**Issue by LImoritakeU** [digoal/blog#23]
如題：

百度盤的連結顯示404失效

**Comment by digoal** [comment]
正常呀

**Comment by digoal** [comment]
![image](https://user-images.githubusercontent.com/1920239/37903823-eeb965ec-312b-11e8-8245-0a680c1ae308.png)

**Comment by LImoritakeU** [comment]
噢...看來是被GFW了，我跳進去試試，謝謝德哥
