### ISSUE TITLE
OpenStreetMap import will break if links aren't updated before May 7

### ISSUE THREAD

**Issue by grischard** [digoal/blog#25]
http://planet.openstreetmap.org is available over https, and will [start redirecting to https on 2018-05-07](https://github.com/openstreetmap/operations/issues/200).

Your project [seems to be using osmosis](https://github.com/digoal/blog/search?q=%22http%3A%2F%2Fplanet.openstreetmap.org%22+osmosis), which [will not follow redirects by default](https://trac.openstreetmap.org/ticket/5483).

Would it please be possible to update all files from `http://planet.openstreetmap.org` to `httpS://planet.openstreetmap.org` before then?

Ideally, would it be possible to make all requests to openstreetmap.org over https? All services respond over https and will start redirecting soon.

**Comment by digoal** [comment]
HI， thank you , updated.
