### ISSUE TITLE
关于分区表中使用类似on conflict 语句限制

### ISSUE THREAD

**Issue by Mingdr** [digoal/blog#27]
我看了德哥的博客说pg 11支持这类语句，但是现在还是10.3版本，如何下载11版本测试呢，另外有没有什么方式也能实现 on conflict update 这种功能呢。我试了触发器，好像实现不了。

**Comment by kxjhlele** [comment]
pg11beta1版本发布了，可以下载编译 或者 pg10可以添加on conflict dothing的补丁，但是不支持 on conflict update
