### ISSUE TITLE
WAL日志的创建时间或恢复时间可否查询？可以的话该如何查询

### ISSUE THREAD

**Issue by Gopfu** [digoal/blog#3]
徳哥，感谢你的博客分享，我想请教下WAL日志的创建时间或恢复时间可否查询？可以的话该如何查询。我知道备份后backup_label里面有个START TIME，pg_xlogdump日志也没有关于时间的描述。

**Comment by Gopfu** [comment]
找到了，pg_xlogdump 后grep 下commit，事务提交的时间点就找到了。呃呃

**Comment by digoal** [comment]
好的谢谢。
