### ISSUE TITLE
请问pg10 1TB 单机TPCH到底能跑多快？

### ISSUE THREAD

**Issue by qub01** [digoal/blog#40]
https://github.com/digoal/blog/blob/master/201707/20170703_01.md 
文章指出 pg10和deepgreen能力相当，给了deepgreen在1TB的TPCH能力。又给了一个例子说明小数据量下，pg10和deepgreen旗鼓相当。 但是没有在原文中看到PG10在单机下跑1TB的TPCH到底是多少，请问博主能给出数据吗？

**Comment by digoal** [comment]
没有1T的数据，估计PG目前的版本还有挑战。zedstore，PG 12以上版本，可以试试。其他的版本就先别跑这么大数据量了。低版本一定要试试的话考虑  https://vitessedata.com/
