### ISSUE TITLE
关于"实时数据交换平台 - BottledWater-pg with confluent"博客中的架构问题

### ISSUE THREAD

**Issue by sd886393** [digoal/blog#5]
德哥
  想请教一下,图中所述的为相关数据先经过了PG数据库,再通过插件导入Kafka,最终消费.
  为何不是直接导入到Kafka再进入PG呢?这样从可用的角度上是不是更好?还是博客中提到的另有优势呢?
  还是说是重点在于使用bottledwater-pg 这个插件的使用情景限制住了?
谢谢!

**Comment by digoal** [comment]
这个架构是很灵活的，看业务的需求。
bottledwater-pg这个插件是指进入了数据库的数据，如何试试分享给其他平台。

**Comment by sd886393** [comment]
好的~ 多谢德哥
