### ISSUE TITLE
Greenplum执行了vacuum freeze，从节点的age都降下来了，主节点却一点儿不降

### ISSUE THREAD

**Issue by Annqi** [digoal/blog#51]
请教一下，greenplum上按节点执行了vacuum freeze，从节点的age都降了，而主节点依旧不降。执行vacuum freeze日志显示执行成功，但实际没有效果。
已检查没有临时表和schema。
请教大神指点。

![image](https://user-images.githubusercontent.com/22704285/53958087-24de9480-411b-11e9-9653-479fb5d4f8ce.png)

![image](https://user-images.githubusercontent.com/22704285/53958066-142e1e80-411b-11e9-8e7f-8cd774ebb095.png)

**Comment by digoal** [comment]
kill long query|xact|2pc

**Comment by Annqi** [comment]
您好，邮件已收到，谢谢~
