### ISSUE TITLE
PostgreSQL 递归查询的效率问题

### ISSUE THREAD

**Issue by lincolnkingxu** [digoal/blog#57]
德哥，Postgre查询树形结构的数量，
WITH RECURSIVE sub_member AS (
  SELECT a.*, 0 AS level FROM member a WHERE id = 5
  UNION ALL
  SELECT b.*, level+1 FROM member b
    INNER JOIN sub_member c ON b.parent_id = c.id
) SELECT count(*) FROM sub_member WHERE id <> 5;
上百万的记录，这样查询出来要十几秒，该怎样去优化？

**Comment by digoal** [comment]
你看一下是不是没有用到索引。百万的数据量肯定不用这么久的。
```
explain (analyze,verbose,timing,costs,buffers) WITH RECURSIVE sub_member AS (
SELECT a.*, 0 AS level FROM member a WHERE id = 5
UNION ALL
SELECT b.*, level+1 FROM member b
INNER JOIN sub_member c ON b.parent_id = c.id
) SELECT count(*) FROM sub_member WHERE id <> 5;
```
