### ISSUE TITLE
PG对于JSONB的支持问题

### ISSUE THREAD

**Issue by wowojyc** [digoal/blog#58]
如果某个字段是Jsonb的，存储的json数据，能否对json数据中的某个字段进行聚合操作或者关联操作呢

**Comment by digoal** [comment]
可以的，及时是存储的json，也可以在查询时转换为jsonb。```cast (column as jsonb)```或者```col::jsonb```, 如果需要索引支持，可以使用表达式索引。

**Comment by wowojyc** [comment]
> 可以的，及时是存储的json，也可以在查询时转换为jsonb。`cast (column as jsonb)`或者`col::jsonb`, 如果需要索引支持，可以使用表达式索引。

也可以进行sum或者count，甚至和其他表的某些字段做join，是吧？除了不能当外键(因为不是真实存在的物理列)?
