### ISSUE TITLE
请教一个Bitmap Heap Scan的问题（PostgreSQL 9.5版本）

### ISSUE THREAD

**Issue by eingmarra** [digoal/blog#61]
explain ANALYSE select user_nickname, rating from plat_user where user_nickname like '%小宝%' order by rating limit 10;

表中有建过索引：CREATE INDEX "plat_user$nickname" ON plat_user USING gin (**user_nickname gin_bigm_ops, rating**)

有看过一些资料，似乎说gin的索引，实现有个小瑕疵，他会先做Bitmap Index Scan，再进行Bitmap Heap Scan。我的实际运行结果如下（用了17秒，总共表中数据大概2亿行左右）：

Limit  (cost=5480.08..5480.11 rows=10 width=31) (actual time=17172.258..17172.260 rows=10 loops=1)
  ->  Sort  (cost=5480.08..5482.22 rows=857 width=31) (actual time=17172.256..17172.256 rows=10 loops=1)
        Sort Key: rating
        Sort Method: top-N heapsort  Memory: 26kB
        ->  **_Bitmap Heap Scan_** on plat_user  (cost=2094.64..5461.56 rows=857 width=31) (actual time=_12.365..17162.804_ rows=13200 loops=1)
              Recheck Cond: (user_nickname ~~ '%小宝%'::text)
              Heap Blocks: exact=13066
              ->  Bitmap Index Scan on "plat_user$nickname"  (cost=0.00..2094.43 rows=857 width=0) (actual time=9.651..9.651 rows=13687 loops=1)
                    Index Cond: (user_nickname ~~ '%小宝%'::text)
Planning time: 0.135 ms
Execution time: 17172.290 ms

问题如下：
1.最新版的PostgreSQL是否对gin有所改进，是否能直接做Bitmap Index Scan，而不用再次Bitmap Heap Scan（这个感觉速度超慢）？

2.因为是新手，接手别人的项目，是否建的索引有问题？（公司的要求比较简单，就是**_like %昵称片段% + rating_** 排序。）

谢谢各位大哥，帮我看看！

**Comment by eingmarra** [comment]
用了预加载模块pg_prewarm，情况有所缓解

请问，预装载的 buffer cache 大小，是用SELECT pg_size_pretty(pg_**total**_relation_size('plat_user'));
还是SELECT pg_size_pretty(pg_relation_size('plat_user'));呢？

即pg_**total**_relation_size表示 plat_user表数据库+plat_user表索引
还是只需要加plat_user表数据就可以了？即大小设置为：pg_relation_size的大小？

谢谢！

**Comment by digoal** [comment]
bitmap scan的原理, 先扫描index然后根据block顺序扫描对应heap. 所以阶段都是正确的.
问题是数据如果很分散或者索引放大了会导致大量废弃的IO. 
例如你这个是两个字符的模糊查询, 应该使用另一种插件或方法
pg_bigm
or
https://github.com/digoal/blog/blob/master/202003/20200330_01.md
