### ISSUE TITLE
请教一个SQL优化的问题：获取每个分组最近15条记录

### ISSUE THREAD

**Issue by xmings** [digoal/blog#68]
有一个业务场景需要每个分组取最近15条记录计算平均值，但每个分组都有上千万的数据量，我们在PG中通过row_number() over(partition by .....) 的方式给每个分组的记录编号，然后取编号<=15的记录再计算，但计算时间最少需要9s。借宝地请教给位大拿有什么办法优化吗？

**Comment by digoal** [comment]
用递归, 参考
[《递归+排序字段加权 skip scan 解决 窗口查询多列分组去重的性能问题》](202006/20200615_01.md)
