### ISSUE TITLE
pglogical_dependency.c:236: error

### ISSUE THREAD

**Issue by mawenbin666** [digoal/blog#71]
1. 安装pglogical的时候报错，

version:pglogical-REL2_3_0

`pglogical_dependency.c:235: error: static declaration of ‘AcquireDeletionLock’ follows non-static declaration
/usr/local/postgresql-12.3/include/server/catalog/dependency.h:145: note: previous declaration of ‘AcquireDeletionLock’ was here
pglogical_dependency.c:236: error: static declaration of ‘ReleaseDeletionLock’ follows non-static declaration
/usr/local/postgresql-12.3/include/server/catalog/dependency.h:147: note: previous declaration of ‘ReleaseDeletionLock’ was here
gmake: *** [pglogical_dependency.o] Error 1`

**Comment by digoal** [comment]
解决了吗? 可以发到pglogical开源项目的issue去问一下

**Comment by mawenbin666** [comment]
> 解决了吗? 可以发到pglogical开源项目的issue去问一下

解决了，谢谢
