### ISSUE TITLE
PostgreSQL 大量IO扫描、计算浪费的优化 - 推荐模块, 过滤已推荐. (热点用户、已推荐列表超大) 这篇文章内容似乎有误

### ISSUE THREAD

**Issue by zxiy** [digoal/blog#72]
https://github.com/digoal/blog/blob/master/202006/20200601_01.md

`两种优化思路:`
这一部分的代码示例，与这篇文章无关，似乎与后面一篇解密的文章串内容了？

**Comment by digoal** [comment]
加密的内容, 不能对外
