### ISSUE TITLE
20200322_01.md文档描述错误

### ISSUE THREAD

**Issue by yuxiaobin** [digoal/blog#73]
https://github.com/digoal/blog/blob/master/202003/20200322_01.md#%E5%85%AB%E6%95%B0%E6%8D%AE%E5%BA%93%E4%BA%A7%E5%93%81%E5%BE%88%E5%A4%9A-%E6%80%8E%E4%B9%88%E5%81%9A%E5%88%B0%E6%B7%B1%E5%BA%A6%E5%88%86%E6%9E%90

第2点：
2、聘请外部技术顾问

推荐, **没屁股**, 比较公正

这个是输入法问题吧？

**Comment by digoal** [comment]
没问题, 通熟易懂的语言, 屁股决定脑袋, 内部人员通常不能客观的表达观点.
