### ISSUE TITLE
pg中扩展IVFFlat和HNSW索引的搜索速度问题

### ISSUE THREAD

**Issue by ShuiXianhua** [digoal/blog#74]
德哥你好，请教一下，pase插件中扩展的IVFFlat索引和HNSW索引，和其他的IVFFlat和HNSW实现相比（比如faiss库中集成的IVFFlat和HNSW算法），在搜索速度上会有大幅度的变慢吗？按照我的理解，因为特征的相似度计算需要特征向量，pg中集成这两种索引，在搜索时，每次计算两个特征的相似度都需要去加载特征向量，因此速度会变慢，faiss库中的实现，也做了一些并行优化，不知道pase插件的搜索性能怎么样。
pg小白，期待回复！

**Comment by digoal** [comment]
可以加入我们钉钉群, 我让研发同学和你讨论下.
这个是文档: https://help.aliyun.com/document_detail/147837.html
可以提前了解一下

**Comment by digoal** [comment]
钉钉群二维码在github readme里面有
