### ISSUE TITLE
求助版本号12的数据库密码忘了还能找回吗

### ISSUE THREAD

**Issue by ishangxue** [digoal/blog#77]
用户 postgres 的口令给忘记了，用网上搜到的方法 把MD5 修改为trust 还是不可以，扔就提示我输入 用户 postgres 的口令

H:\PostgreSQL\12\bin>psql -U postgres
用户 postgres 的口令：（这个密码我忘记了）
psql: 错误: 无法连接到服务器：fe_sendauth: no password supplied

**Comment by digoal** [comment]
可以配置pg_hba.conf , 使用无密码登陆.  需要reload.
