### ISSUE TITLE
主从节点数据不一致，如何同步两边数据？

### ISSUE THREAD

**Issue by qax-mamo** [digoal/blog#78]
因为PG master出现故障，master有未同步到slave的数据，PG slave切换为主节点，切换为主节点的slave存在增量数据，现在的需求是两边数据都不丢失的情况下如何进行数据同步？非常感谢。

**Comment by digoal** [comment]
没有
这种需求你需要使用3节点或者更多节点, 采用同步复制防止丢数据.

2节点old master还活的情况下, 补增量只能采用逻辑方法, 解析wal日志或者审计日志, 补数据. 非主流操作, 没有产品支持, 自己动手.
