### ISSUE TITLE
请教postgreSQL商业化应用问题

### ISSUE THREAD

**Issue by astwyg** [digoal/blog#8]
Digoal, 您好!

我想请教一个关于postgreSQL商业化的问题. 山东瀚高好像是目前国内唯一提供企业级PostgreSQL部署和维护的公司, 他们也推出了自己的一个商业化版本. 我想请教一下, 对于中等规模企业来说, 如果希望通过PostgreSQL完成Oracle替代, 选择一家商业化服务公司是否靠谱, 以及您对山东瀚高有什么看法, 是否有其他更好的推荐?

感谢!

**Comment by digoal** [comment]
山东瀚高还不错哦，是中国开源软件推进联盟PostgreSQL中国分会的核心成员企业。
如果要关注企业支持这块的信息，可以关注一下中国开源软件推进联盟PostgreSQL中国分会的动态。

**Comment by astwyg** [comment]
想再向您请教一个行业的问题: 前几年(05年-12年)国内一直没有出现基于PostgreSQL或者其他开源数据库的商业数据库公司, 瀚高也是这两年逐渐开始做, 规模也还不是很大, 您怎么看前几年国内一直没有基于开源的商业数据库公司?

感谢!
