### ISSUE TITLE
期望PG功能完善

### ISSUE THREAD

**Issue by pcsuc007** [digoal/blog#84]
行业:传统制造业
期望功能:PG长时间空闲连接可以自动回收并释放资源;
解决什么问题:PG空闲连接进程把内存耗尽;
期望功能分级: 有就一定用

**Comment by digoal** [comment]
HI, 这个功能有插件能支持
https://github.com/digoal/blog/blob/master/202007/20200724_01.md
另外, 在应用端通常也能配置连接生命周期.
还有, 对于连接较多的场景, pg shared buffer建议开启huge page.

**Comment by pcsuc007** [comment]
好像还是不行啊，进程一直没有释放，我安装了pg_timeout,该配置的也都配置了，我用Navicate做了个测试，还是一直idle状态，没有被kill掉。


1634108459@qq.com
 
发件人： Digoal.zhou
发送时间： 2020-11-06 23:05
收件人： digoal/blog
抄送： pc007; Author
主题： Re: [digoal/blog] 期望PG功能完善 (#84)
HI, 这个功能有插件能支持
https://github.com/digoal/blog/blob/master/202007/20200724_01.md
另外, 在应用端通常也能配置连接生命周期.
还有, 对于连接较多的场景, pg shared buffer建议开启huge page.

**Comment by belongwqz** [comment]
希望pg自身支持简单配置的高可用功能，而不是通过第三方软件实现。
