### ISSUE TITLE
为什么我的表只有16w，但是查询却很慢，我有索引的

### ISSUE THREAD

**Issue by xuan52rock** [digoal/blog#87]
create index index_title_gin on tikutable using gin (title);
select set_limit(0.9);
select id,title,similarity(title,'下列关于我国法律部门和法律体系的表述中，不正确的是') as sm from tikutable order by sm desc limit 5;

**Comment by digoal** [comment]
你需要看看执行计划,

**Comment by xuan52rock** [comment]
你是说explain吗

**Comment by xuan52rock** [comment]
![image](https://user-images.githubusercontent.com/9817007/103719993-4d7c9180-5005-11eb-92c5-d4c02e923da8.png)
帮忙看看

**Comment by xuan52rock** [comment]
Limit  (cost=10419.54..10420.12 rows=5 width=328)
  ->  Gather Merge  (cost=10419.54..25902.99 rows=132706 width=328)
        Workers Planned: 2
        ->  Sort  (cost=9419.52..9585.40 rows=66353 width=328)
              Sort Key: (similarity(title, '下列关于我国法律部门和法律体系的表述中，不正确的是'::text)) DESC
              ->  Parallel Seq Scan on wwwacc5_new_tiku_question2  (cost=0.00..8317.42 rows=66353 width=328)

**Comment by xuan52rock** [comment]
Limit  (cost=10419.54..10420.12 rows=5 width=328)
  ->  Gather Merge  (cost=10419.54..25902.99 rows=132706 width=328)
        Workers Planned: 2
        ->  Sort  (cost=9419.52..9585.40 rows=66353 width=328)
              Sort Key: (similarity(title, '下列关于我国法律部门和法律体系的表述中，不正确的是'::text)) DESC
              ->  Parallel Seq Scan on tikutable  (cost=0.00..8317.42 rows=66353 width=328)

**Comment by digoal** [comment]
看样子没有用索引, 你可以看看为什么没有使用索引, 是不是中文没有被正确的切分. 例如使用了lc_ctype=C
