### ISSUE TITLE
PG10.15进行3小时压测后，top查看内存无空闲内存问题

### ISSUE THREAD

**Issue by java30kcoding** [digoal/blog#91]
## 机器配置

+ 8C32G
+ 1TB高IO磁盘，IOPS上限5,000
+ CPU型号为Intel(R) Xeon(R) Gold 6161 CPU @ 2.20GHz

## PG配置

>  参考的：https://github.com/digoal/blog/blob/master/201611/20161121_01.md
>
> 进行了从512到32G的配置缩减

## 2kw数据复杂数据压测

> 参考：https://github.com/digoal/blog/blob/master/201203/20120313_01.md

```shell
./pgbench -M prepared -r -c 8 -f login.sql -j 8 -n -T 60
# 21000TPS
```

## 压测3小时命令
> 压了230分钟左右停止了压测命令

```shell
./pgbench -M prepared -r -c 8 -f login.sql -j 8 -n -T 1800000
```

## 压测一天过后的内存状态

KiB Mem : 32780852 total,   267268 free,   356752 used, 32156832 buff/cache
KiB Swap:  4194300 total,  4194300 free,        0 used. 23003220 avail Mem

求问德哥，这个状态正常嘛？感激不尽~

**Comment by java30kcoding** [comment]
## 压测时服务器状态

+ CPU占用平均94%，高峰96.53%
+ 磁盘写IOPS平均1050，最高1132

**Comment by digoal** [comment]
正常, 大部分都是buffer cache
