### ISSUE TITLE
视频回放链接无效

### ISSUE THREAD

**Issue by leoyey** [digoal/blog#93]
下面文章的视频回放链接无效，请更新一下，多谢。
https://github.com/digoal/blog/blob/master/202105/20210503_01.md

**Comment by leoyey** [comment]
如果是像其他文章，只是 yq.aliyun和developer.aliyun 区别，是可以根据视频ID正确找到developer.aliyun中的视频的。
不过上面这个文章的视频地址是 https://github.com/digoal/blog/blob/master/202105/xx ，是一个错误的链接。如果可以，请放一个视频ID，我可以自己去developer.aliyun找视频。

**Comment by digoal** [comment]
抱歉,这个还没录制, 等录制好了会更新
