### ISSUE TITLE
请教，在网络不通的网闸环境，两端的postgres如何增量同步数据？

### ISSUE THREAD

**Issue by chaizp** [digoal/blog#98]
请教，我们有一个跨网闸的环境，两个网络互相不通，中间存在网闸可以通过ftp摆渡文件。
两端都各有一台postgres服务器，并且两端都会生产数据，有什么方式可以将两端产生数据通过网闸摆渡的方式增量同步呢？

最开始想使用copy，但会出现ID存在问题，试过kettle做Excel同步更新，但总有一个表在Kettle中报错，并且有张表没有时间字段（设计时的坑）；
也想过使用归档的方式，但两端都会产生数据，并且归档需要重启；

环境CentOS7.3   Docker Postgres 10.1

**Comment by digoal** [comment]
有PK的话可以使用逻辑复制
